apiVersion: apps/v1
kind: Deployment
metadata:
   name: mysql-deployment
   labels:
      appName: node-mysql-deployment
spec:
   replicas: 1
   selector:
     matchLabels:
        appName: node-mysql-app
   template:
      metadata:
         name: mysql-pod
         labels:
            appName: node-mysql-app
            tier: backend
      spec:
        containers:
             - name: node-mysql
               image: mysql
               ports:
                 - containerPort: 3306
               volumeMounts:
                 - mountPath: /var/lib/mysql
                   name: pv
               env:
               - name: MYSQL_ROOT_PASSWORD
                 value: root
               - name: MYSQL_DATABASE
                 value: sample
        volumes:
              - name: pv
                emptyDir: {}




