apiVersion: v1
kind: Service
metadata:
  name: mysql
  labels:
    name: mysql-service
    app: node-mysql-app
spec:

  ports:
    - port: 3306
      targetPort: 3306
  selector:
    appName: node-mysql-app
    tier: backend
