apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
    name: node-autoscaler
spec:
   scaleTargetRef: 
       apiVersion: apps/v1
       kind: Deployment
       name: node-app-deployment
   minReplicas: 2
   maxReplicas: 5
   targetCPUUtilizationPercentage: 50


